version: 2

project_name: anytls
builds:
  - id: anytls-client
    binary: anytls-client
    dir: cmd/client
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
      - -buildvcs=false
      - -tags=with_utls
    ldflags:
      - -s -w
  - id: anytls-server
    binary: anytls-server
    dir: cmd/server
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
      - -buildvcs=false
      - -tags=with_utls
    ldflags:
      - -s -w
archives:
  - id: anytls-client-binary
    ids:
      - anytls-client
    formats:
      - binary
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
  - id: anytls-server-binary
    ids:
      - anytls-server
    formats:
      - binary
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
  - id: anytls
    ids:
      - anytls-client
      - anytls-server
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - zip
checksum:
  name_template: checksums.txt
release:
  extra_files:
    - glob: anyreality.yaml
    - glob: deploy/systemd/anytls-anyreality.service
