name: ci

on:
  push:
    branches:
      - '**'
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Test
        run: go test ./...

      - name: Test with Reality tag
        run: go test -tags with_utls ./...

      - name: Build client
        run: go build -tags with_utls -trimpath -buildvcs=false ./cmd/client

      - name: Build server
        run: go build -tags with_utls -trimpath -buildvcs=false ./cmd/server

  snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true

      - name: GoReleaser snapshot
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --snapshot --clean
